apiVersion: v1
kind: Pod
metadata:
  name: almalinux-pod
  labels:
    app: almalinux-app
spec:
  containers:
  - name: almalinux-container
    image: almalinux:latest
    ports:
    - containerPort: 80
    command: [ "sleep", "3600" ]

---
apiVersion: v1
kind: Service
metadata:
  name: almalinux-service
spec:
  type: NodePort
  selector:
    app: almalinux-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 30013
