apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: localhost:5000/alpine-hello:latest
        command: ["sh", "-c", "while true; do echo 'Hello from Alpine!'; sleep 5; done"]
