apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine-app
spec:
  containers:
  - name: alpine-container
    image: alpine:latest
    ports:
    - containerPort: 80
    command: [ "sleep", "3600" ]

---
apiVersion: v1
kind: Service
metadata:
  name: alpine-service
spec:
  type: NodePort
  selector:
    app: alpine-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 30014
