apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
  - name: alpine
    image: localhost:5000/alpine-hello:latest
    command: ["sh", "-c", "echo 'Hello from Alpine!' && sleep 3600"]
