apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
spec:
  containers:
  - name: busybox-container
    image: localhost:5000/busybox:latest
    command: ["sleep", "3600"]
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
spec:
  type: NodePort
  selector:
    app: busybox
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30021
