apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod1
  labels:
    app: httpd11
spec:
  containers:
  - name: httpd1
    image: localhost:5000/httpd:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: httpd11
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 80
    nodePort: 30016
