apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx11
spec:
  containers:
  - name: nginx1
    image: localhost:5000/ngin1:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx11
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 30010
