apiVersion: v1
kind: Pod
metadata:
  name: portainer-pod
  labels:
    app: portainer
spec:
  containers:
  - name: portainer
    image: localhost:5000/portainer:latest
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: portainer-data
      mountPath: /data
  volumes:
  - name: portainer-data
    emptyDir: {}
