apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  containers:
    - name: postgres
      image: localhost:5000/postgres-custom:latest
      env:
        - name: POSTGRES_USER
          value: "aks"
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_DB
          value: "mydatabase"
      ports:
        - containerPort: 5432
