apiVersion: v1
kind: Pod
metadata:
  name: aks-pod
  labels:
    app: aks-app
spec:
  containers:
  - name: aks-container
    image: redis:latest
    ports:
    - containerPort: 6379
    command: [ "redis-server" ]

---
apiVersion: v1
kind: Service
metadata:
  name: aks-service
spec:
  type: NodePort
  selector:
    app: aks-app
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30013
